# Generated by Django 5.2.8 on 2026-03-30 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/about/')),
                ('background_summary', models.TextField()),
                ('quick_facts', models.JSONField(blank=True, default=dict)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About section',
                'verbose_name_plural': 'About section',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('issuer', models.CharField(max_length=160)),
                ('issue_date', models.DateField()),
                ('credential_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('cv_download_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact information',
                'verbose_name_plural': 'Contact information',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contact_attachments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('response_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_name', models.CharField(max_length=160)),
                ('institution_name', models.CharField(max_length=180)),
                ('location', models.CharField(max_length=140)),
                ('field_of_study', models.CharField(max_length=140)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gpa_cgpa', models.CharField(blank=True, max_length=40)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='education/')),
            ],
            options={
                'ordering': ['order', '-end_date', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(max_length=140)),
                ('company_name', models.CharField(max_length=140)),
                ('location', models.CharField(max_length=140)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('key_responsibilities', models.JSONField(blank=True, default=list)),
                ('technologies_used', models.JSONField(blank=True, default=list)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='experiences/')),
            ],
            options={
                'ordering': ['order', '-start_date', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.TextField()),
                ('headline_image', models.ImageField(blank=True, null=True, upload_to='profile/hero/')),
                ('cta_button_text', models.CharField(max_length=50)),
                ('cta_button_url', models.CharField(max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50)),
                ('secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero section',
                'verbose_name_plural': 'Hero section',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies_used', models.JSONField(blank=True, default=list)),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Archived', 'Archived')], default='Completed', max_length=20)),
                ('detailed_description', models.TextField()),
                ('key_features', models.JSONField(blank=True, default=list)),
                ('lessons_learned', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'ordering': ['order', '-start_date', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120)),
                ('logo_text', models.CharField(blank=True, max_length=60)),
                ('seo_title', models.CharField(max_length=160)),
                ('seo_description', models.TextField()),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
                ('accent_text', models.CharField(blank=True, max_length=60)),
                ('availability_status', models.CharField(blank=True, max_length=120)),
                ('footer_note', models.CharField(blank=True, max_length=160)),
                ('resume_label', models.CharField(default='Download CV', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=60)),
                ('profile_url', models.URLField()),
                ('icon_code', models.CharField(help_text='Font Awesome class name such as fa-brands fa-linkedin-in', max_length=80)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120)),
                ('author_title', models.CharField(max_length=140)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('testimonial_text', models.TextField()),
                ('company', models.CharField(max_length=140)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Tools', 'Tools'), ('Data Analysis', 'Data Analysis'), ('Cloud', 'Cloud')], max_length=30)),
                ('skill_name', models.CharField(max_length=120)),
                ('proficiency_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class name such as fa-brands fa-python', max_length=80)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
                'unique_together': {('category', 'skill_name')},
            },
        ),
    ]
