# Generated by Django 5.2.8 on 2026-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('author', models.CharField(default='Arjun Singh', max_length=120)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Django', 'Django'), ('React', 'React'), ('Data', 'Data'), ('Cloud', 'Cloud'), ('Career', 'Career')], max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('published_date', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
                ('read_time', models.PositiveSmallIntegerField(default=5)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order', '-published_date', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=60, unique=True)),
                ('meta_title', models.CharField(max_length=160)),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('og_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Page metadata',
                'verbose_name_plural': 'Page metadata',
            },
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='masters_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='company',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='message_type',
            field=models.CharField(choices=[('Project Inquiry', 'Project Inquiry'), ('Collaboration', 'Collaboration'), ('General', 'General')], default='General', max_length=30),
        ),
        migrations.AddField(
            model_name='education',
            name='relevant_coursework',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Full-Stack', 'Full-Stack'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Data', 'Data')], default='Full-Stack', max_length=20),
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
