# Generated by Django 5.2.8 on 2026-03-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_blogpost_pagemetadata_aboutsection_achievements_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
