# Generated by Django 5.2.8 on 2026-04-09 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_emailcampaign_subscriber_unsubscribe_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='audience',
            field=models.CharField(choices=[('all_active', 'All active subscribers'), ('newest_30_days', 'Subscribers from the last 30 days'), ('newest_90_days', 'Subscribers from the last 90 days')], default='all_active', max_length=30),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('portfolio_update', 'Portfolio update'), ('announcement', 'Announcement'), ('marketing', 'Marketing')], default='marketing', max_length=30),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='featured_projects',
            field=models.ManyToManyField(blank=True, related_name='email_campaigns', to='portfolio_app.project'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='headline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='include_latest_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Only visible in admin/dashboard. Use it for planning and follow-ups.'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='intro',
            field=models.TextField(blank=True, help_text='Short intro shown above the main content.'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='latest_projects_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='open_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sending_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template_style',
            field=models.CharField(choices=[('editorial', 'Editorial'), ('minimal', 'Minimal'), ('launch', 'Launch')], default='editorial', max_length=20),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='test_recipients',
            field=models.CharField(blank=True, help_text='Comma-separated email addresses for preview sends before a full launch.', max_length=255),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='track_clicks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='track_opens',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('test', 'Test')], default='pending', max_length=20)),
                ('subject_snapshot', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='portfolio_app.emailcampaign')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='portfolio_app.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'email'), name='unique_campaign_email_delivery')],
            },
        ),
    ]
