# Generated by Django 5.2.8 on 2026-04-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0014_emailcampaign_audience_emailcampaign_campaign_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailDelivery',
        ),
        migrations.DeleteModel(
            name='EmailCampaign',
        ),
    ]
