# Generated by Django 5.1.15 on 2026-05-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0016_subscriber_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='WhatsApp', max_length=40)),
                ('title', models.CharField(default='Start a conversation', max_length=90)),
                ('subtitle', models.CharField(default='Usually replies within a few hours', max_length=120)),
                ('description', models.TextField(default='Share your project, question, or collaboration idea and continue the conversation on WhatsApp.')),
                ('phone_number', models.CharField(help_text='Include country code, for example 919876543210 or +91 98765 43210.', max_length=32)),
                ('prefilled_message', models.CharField(blank=True, default='Hello, I came across your portfolio and would like to connect.', max_length=255)),
                ('button_text', models.CharField(default='Open WhatsApp', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'WhatsApp widget',
                'verbose_name_plural': 'WhatsApp widget',
            },
        ),
    ]
